pixelmon:
  hookvault: false
ic2:
  canceled:
    LaserEvent-Shoot: false
    LaserEvent-HitsEntity: false
    LaserEvent-HitsBlock: false
    LaserEvent-Explodes: false
    LaserEvent-all: false
    LaserEvent: false
    Explosion: false